### ISSUE TITLE
Current master branch broken by plink work-in-progress

### ISSUE THREAD

**Issue by draxil** [salva/p5-Test-SSH#3]
The master branch doesn't work due to the half finished work in the "working on running remote command with plink" commit. Is there any chance this work could be hived off in a branch somewhere so that there is a clean functional place to get the latest version of this? As the CPAN version doen't have the latest patches I'm currently maintaining my own, but it'd be really nice just to be able to pull from the canonical github version without worry. 

Thanks!
(and sorry for pestering)

**Comment by salva** [comment]
Do it yourself, you have the rights now!!!

Seriously, my plan for Test::SSH was to move it inside Net::SSH::Any so that I could reuse some infrastructure available there... but that has been going much slower than what I expected and so, Test::SSH has remained dormant and mostly unmaintained for a long time.

As you have already have a proper working version ready, I would really appreciate if you could help me to make a new release of that.

You can rearrange the git branches if you want too, renaming the broken `master` as `development` for instance, and getting `master` to the latest stable version plus your patches.

**Comment by draxil** [comment]
Done and thanks.
